services:

  ollama-service:
    image: ollama/ollama:0.5.4
    volumes:
      - ./ollama-data:/root/.ollama
    ports:
      - 11434:11434

  download-tools-llm:
    image: curlimages/curl:8.6.0
    entrypoint: ["curl", "ollama-service:11434/api/pull", "-d", "{\"name\": \"qwen2.5-coder:1.5b\"}"]
    depends_on:
      ollama-service:
        condition: service_started

  run-tools-code:
    build: .
    command: go run main.go; sleep infinity
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
    volumes:
      - ./:/app
    depends_on:
      download-tools-llm:
        condition: service_completed_successfully

    develop:
      watch:
        - action: rebuild
          path: ./main.go
          target: /app
        - action: rebuild
          path: ./prompt.txt
          target: /app 
