services:

  ollama-service:
    image: ollama/ollama:0.5.4
    volumes:
      - ./ollama-data:/root/.ollama
    ports:
      - 11434:11434

  download-tools-llm-2:
    image: curlimages/curl:8.6.0
    entrypoint: ["curl", "ollama-service:11434/api/pull", "-d", "{\"name\": \"qwen2.5:1.5b\"}"]
    depends_on:
      ollama-service:
        condition: service_started

  download-tools-llm-3:
    image: curlimages/curl:8.6.0
    entrypoint: ["curl", "ollama-service:11434/api/pull", "-d", "{\"name\": \"qwen2.5-coder:1.5b\"}"]
    depends_on:
      ollama-service:
        condition: service_started


  run-tools-code:
    image: golang:1.23.4-alpine
    command: sleep infinity
    #entrypoint: 
    #  - /bin/sh
    #  - -c
    #  - cd /app && go mod tidy && go run main.go
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      #- TOOLS_LLM=allenporter/xlam:1b
      - TOOLS_LLM=qwen2.5-coder:1.5b
    volumes:
      #- ./:/app
      - '..:/workspaces:cached'
    depends_on:
      download-tools-llm-3:
        condition: service_completed_successfully
      download-tools-llm-2:
        condition: service_completed_successfully



  #ubuntu:
  #  image: ubuntu:22.04
  #  tty: true
  #  command: tail -f /dev/null
  #  volumes:
  #    - ./:/app    
